"""Shared custom catalog authoring service for CLI and HTTP clients."""

from .models import (
    RecipeDraftRequest,
    RecipePublishRequest,
    ResourceAddRequest,
    ResourceEditorCatalogResponse,
    ResourceIdSuggestionRequest,
    ResourceInspectRequest,
    ResourcePublicationPreview,
    ResourceUpdateRequest,
)
from .service import (
    CatalogAuthoringError,
    add_resource,
    authoring_capabilities,
    inspect_resource_source,
    preview_resource,
    publish_recipe_draft,
    resource_editor_catalog,
    resource_editor_resource,
    save_recipe_draft,
    suggest_resource_id,
    update_resource,
    validate_recipe,
    validate_resource_catalog,
)

__all__ = [
    "CatalogAuthoringError",
    "RecipeDraftRequest",
    "RecipePublishRequest",
    "ResourceAddRequest",
    "ResourceEditorCatalogResponse",
    "ResourceIdSuggestionRequest",
    "ResourceInspectRequest",
    "ResourcePublicationPreview",
    "ResourceUpdateRequest",
    "add_resource",
    "authoring_capabilities",
    "inspect_resource_source",
    "preview_resource",
    "publish_recipe_draft",
    "resource_editor_catalog",
    "resource_editor_resource",
    "save_recipe_draft",
    "suggest_resource_id",
    "update_resource",
    "validate_recipe",
    "validate_resource_catalog",
]
