"""Two-tool shadow experiment; deliberately not a production catalog path."""

from __future__ import annotations

import json
import os
import subprocess
import sys
from copy import deepcopy
from dataclasses import replace
from pathlib import Path
from typing import Any

import pytest
from fastapi.testclient import TestClient
from test_service import FakeRuntime

from latentslate_engine import service
from latentslate_engine.ltx23.recipes import LTX23_I2V_POLICY
from latentslate_engine.recipe import ProductPolicy, exposed
from latentslate_engine.wan2214b.recipes import WAN2214B_FLF_POLICY

# Captured from the unmodified starting implementation, never generated by tests.
ORACLE = Path(__file__).parent / "fixtures" / "catalog-ee7e883.json"
PROBES = (service.I2V_ID, service.WAN_FLF_ID)


def _baseline() -> list[dict[str, Any]]:
    return json.loads(ORACLE.read_text(encoding="utf-8"))["tools"]


def _presentation(tool_id: str) -> dict[str, dict[str, Any]]:
    # Service presentation and wire-presence policy, not recipe policy.
    result = {
        "prompt": {
            "label": "Prompt",
            "ui": {"multiline": True, "placeholder": "Describe the shot"},
        },
        "start_image": {
            "label": "Start Image" if tool_id == service.I2V_ID else "First Frame",
        },
        "width": {"label": "Width", "required": True},
        "height": {"label": "Height", "required": True},
        "duration_seconds": {
            "label": "Duration",
            "required": True,
            "ui": {"unit": "seconds"},
        },
        "seed": {"label": "Seed", "required": True},
    }
    if tool_id == service.WAN_FLF_ID:
        result["end_image"] = {"label": "Last Frame"}
    return result


def _project_inputs(
    surface: tuple[dict[str, object], ...],
    presentation: dict[str, dict[str, Any]],
) -> list[dict[str, Any]]:
    """Shadow the existing service descriptors for these two scalar surfaces only."""
    published_constraints = {
        "width": ("min", "step"),
        "height": ("min", "step"),
        "duration_seconds": ("min", "max", "step"),
    }
    inputs = []
    for item in surface:
        key = item["key"]
        display = presentation[key]
        ui = dict(display.get("ui", {}))
        for constraint in published_constraints.get(key, ()):
            ui[constraint] = item["constraints"][constraint]
        inputs.append(
            service._input(
                key,
                display["label"],
                item["type"],
                required=display.get("required", item["required"]),
                default=item.get("default"),
                role=item.get("role"),
                ui=ui or None,
            )
        )
    return inputs


@pytest.fixture(params=PROBES, ids=("ltx-i2v", "wan-flf"))
def probe(request) -> tuple[str, ProductPolicy]:
    policy = (
        LTX23_I2V_POLICY if request.param == service.I2V_ID else WAN2214B_FLF_POLICY
    )
    return request.param, policy


def test_complete_production_catalog_matches_frozen_starting_contract() -> None:
    baseline = _baseline()
    assert service.TOOLS == baseline
    assert service._tool_definitions() == baseline
    assert service.TOOLS_BY_ID == {tool["id"]: tool for tool in baseline}


def test_shadow_projection_matches_frozen_inputs_and_schema(probe) -> None:
    tool_id, definition = probe
    expected = next(tool for tool in _baseline() if tool["id"] == tool_id)
    surface = definition.surface()
    projected = _project_inputs(surface, _presentation(tool_id))
    assert projected == expected["inputs"]
    assert [item["key"] for item in surface] == [
        item["key"] for item in expected["inputs"]
    ]
    assert all(
        not item.get("nullable") and not item.get("collection") for item in surface
    )
    assert all("label" not in item and "ui" not in item for item in surface)
    assert all(item["type"] not in {"artifact", "adapter"} for item in surface)
    exposed_keys = {
        field.capability.key for field in definition.fields if field.exposed
    }
    hidden_keys = {
        cap.key for cap in definition.capabilities.capabilities
    } - exposed_keys
    assert not hidden_keys & {item["key"] for item in projected}

    # Tool identity, canvas, timing and hashing stay on the service side.
    shadow = deepcopy(service.TOOLS_BY_ID[tool_id])
    shadow["inputs"] = projected
    base = {
        key: value
        for key, value in shadow.items()
        if key not in {"schema_hash", "timing"}
    }
    shadow["schema_hash"] = service._schema_hash(base)
    assert shadow == expected
    assert (
        service._schema_hash({**base, "timing": shadow["timing"]})
        != expected["schema_hash"]
    )


def test_semantics_feed_projection_but_presentation_is_service_owned(probe) -> None:
    tool_id, definition = probe
    display = _presentation(tool_id)
    changed = replace(
        definition,
        fields=tuple(
            exposed(field.capability, default="Recipe prompt")
            if field.capability.key == "prompt"
            else exposed(field.capability, default=3.0, minimum=2.0, maximum=4.0)
            if field.capability.key == "duration_seconds"
            else field
            for field in definition.fields
        ),
    )
    projected = {
        item["key"]: item for item in _project_inputs(changed.surface(), display)
    }
    assert projected["prompt"]["default"] == "Recipe prompt"
    assert projected["prompt"]["required"] is False
    assert projected["duration_seconds"]["default"] == 3.0
    assert projected["duration_seconds"]["ui"] == {
        "min": 2.0,
        "max": 4.0,
        "step": 0.5 if tool_id == service.I2V_ID else 0.25,
        "unit": "seconds",
    }
    for semantic, public in zip(changed.surface(), projected.values(), strict=True):
        assert public["key"] == semantic["key"]
        assert public["type"] == semantic["type"]
        assert public.get("role") == semantic.get("role")
        assert public.get("default") == semantic.get("default")
    surface = {item["key"]: item for item in definition.surface()}
    assert surface["seed"]["constraints"] == {"min": 0, "max": 2**64 - 1}
    assert "ui" not in projected["seed"]
    assert "max" in surface["width"]["constraints"]
    assert set(projected["width"]["ui"]) == {"min", "step"}

    display["start_image"]["label"] = "Service label"
    display["prompt"]["ui"] = {"placeholder": "Service hint"}
    redisplayed = _project_inputs(changed.surface(), display)
    assert redisplayed[1]["label"] == "Service label"
    assert redisplayed[0]["ui"] == {"placeholder": "Service hint"}
    assert changed.surface()[1] == surface["start_image"]


def test_recipe_defaults_do_not_mean_optional_wire_inputs(
    probe, tmp_path: Path
) -> None:
    tool_id, definition = probe
    surface = {item["key"]: item for item in definition.surface()}
    expected = next(tool for tool in _baseline() if tool["id"] == tool_id)
    with TestClient(
        service.create_app(home=tmp_path, token="", executor=FakeRuntime())
    ) as client:
        for key in ("width", "height", "duration_seconds", "seed"):
            assert surface[key]["required"] is False
            assert (
                surface[key]["default"]
                == {"width": 512, "height": 512, "duration_seconds": 5.0, "seed": 0}[
                    key
                ]
            )
            inputs = {
                item["key"]: item.get("default", "unused")
                for item in expected["inputs"]
            }
            del inputs[key]
            response = client.post(
                "/v1/jobs",
                json={
                    "tool_id": tool_id,
                    "schema_revision": expected["schema_revision"],
                    "schema_hash": expected["schema_hash"],
                    "inputs": inputs,
                },
            )
            assert response.status_code == 422
            assert response.json() == {
                "error": {"message": "The request is missing required inputs"}
            }


@pytest.mark.parametrize("available", (True, False))
def test_catalog_endpoint_preserves_frozen_contract(
    tmp_path: Path, available: bool
) -> None:
    runtime = FakeRuntime(
        unavailable_operations=set() if available else {"i2v", "wan_flf"}
    )
    expected = []
    for tool in _baseline():
        public = {**tool, "available": available or tool["id"] not in PROBES}
        if not public["available"]:
            family = "LTX" if tool["id"] == service.I2V_ID else "Wan"
            public["unavailable_reason"] = (
                f"Required {family} model files are not installed"
            )
        expected.append(public)
    with TestClient(
        service.create_app(home=tmp_path, token="", executor=runtime)
    ) as client:
        response = client.get("/v1/catalog")
        assert response.status_code == 200
        assert response.json() == {
            "protocol_version": "1.0",
            "engine_version": "0.1.0",
            "bundles": [],
            "tools": expected,
        }


def test_static_catalog_precedes_configuration_and_recipe_binding(
    tmp_path: Path,
) -> None:
    script = """
import json
import sys
import dotenv
def unexpected_configuration(*args, **kwargs):
    raise AssertionError('static catalog must not initialize app configuration')
dotenv.load_dotenv = unexpected_configuration
from latentslate_engine.service import TOOLS
assert 'latentslate_engine.recipe' not in sys.modules
assert 'torch' not in sys.modules
print(json.dumps(TOOLS))
"""
    completed = subprocess.run(
        [sys.executable, "-c", script],
        check=False,
        capture_output=True,
        text=True,
        env={
            **os.environ,
            "LATENTSLATE_ENGINE_HOME": str(tmp_path / "missing-home"),
            "LATENTSLATE_WAN_MODEL_ROOT": str(tmp_path / "missing-models"),
        },
    )
    assert completed.returncode == 0, completed.stderr
    assert json.loads(completed.stdout) == _baseline()


def test_unconfigured_model_files_do_not_remove_catalog_tools(
    tmp_path: Path, monkeypatch
) -> None:
    monkeypatch.setattr(service, "load_dotenv", lambda *args: None)
    monkeypatch.delenv("LATENTSLATE_WAN_MODEL_ROOT", raising=False)
    monkeypatch.delenv("LATENTSLATE_KLEIN9B_VAE", raising=False)
    with TestClient(service.create_app(home=tmp_path, token="")) as client:
        tools = client.get("/v1/catalog").json()["tools"]
        assert all(tool["available"] is False for tool in tools)
        assert [
            {
                key: value
                for key, value in tool.items()
                if key not in {"available", "unavailable_reason"}
            }
            for tool in tools
        ] == _baseline()
