"""Eight-tool projection against the independent pre-recipe catalog."""

from __future__ import annotations

import json
import os
import subprocess
import sys
import time
from copy import deepcopy
from dataclasses import replace
from pathlib import Path
from types import SimpleNamespace
from typing import Any
from uuid import uuid4

import pytest
from fastapi.testclient import TestClient
from test_authoring import _field, _materialize
from test_service import FakeRuntime, _png

from latentslate_engine import catalog, service
from latentslate_engine.authoring import compile_document
from latentslate_engine.authoring_builtins import builtin_documents
from latentslate_engine.catalog import T2V_ID
from latentslate_engine.recipe import ProductPolicy, exposed
from latentslate_engine.service import create_app

# Captured from the unmodified starting implementation, never generated by tests.
ORACLE = Path(__file__).parent / "fixtures" / "catalog-ee7e883.json"
PROBES = {
    catalog.T2V_ID: "LTX23_T2V_POLICY",
    catalog.I2V_ID: "LTX23_I2V_POLICY",
    catalog.FLF_ID: "LTX23_FLF_POLICY",
    catalog.WAN_T2V_ID: "WAN2214B_T2V_POLICY",
    catalog.WAN_I2V_ID: "WAN2214B_I2V_POLICY",
    catalog.WAN_FLF_ID: "WAN2214B_FLF_POLICY",
}


def _baseline() -> list[dict[str, Any]]:
    tools = json.loads(ORACLE.read_text(encoding="utf-8"))["tools"]
    # Revision 3 publishes the existing LTX source/canvas admission rule.
    # Keep the independent pre-recipe oracle and declare only this public delta.
    corrected_hashes = {
        "ltx23.image_to_video": "sha256:be3be547dd665155e162d51a5bea089cfcb0da66116c6e58c1766af04679bb24",
        "ltx23.first_last_frame_to_video": "sha256:b58e76368b442ca723a0e2679db3b5b011870c4eeaba223704192d1190d9de1c",
    }
    for tool in tools:
        if tool["id"] in {catalog.T2V_ID, catalog.I2V_ID, catalog.FLF_ID}:
            tool["timing"]["duration_seconds"]["output_frame_counts"] = [
                {"duration_seconds": half / 2, "frame_count": 8 * (15 * half // 8) + 1}
                for half in range(2, 21)
            ]
        if tool["key"] in corrected_hashes:
            tool["schema_revision"] = 3
            tool["schema_hash"] = corrected_hashes[tool["key"]]
            for item in tool["inputs"]:
                if item["type"] == "image":
                    item["image_dimensions"] = "match_output_canvas"
    return tools


@pytest.fixture(
    params=PROBES,
    ids=("ltx-t2v", "ltx-i2v", "ltx-flf", "wan-t2v", "wan-i2v", "wan-flf"),
)
def probe(request) -> tuple[str, ProductPolicy]:
    return request.param, getattr(catalog, PROBES[request.param])


def test_complete_production_catalog_matches_frozen_starting_contract() -> None:
    baseline = _baseline()
    assert catalog.TOOLS == baseline
    assert catalog._tool_definitions() == baseline
    assert catalog.TOOLS_BY_ID == {tool["id"]: tool for tool in baseline}


def test_production_projection_matches_frozen_inputs_and_schema(probe) -> None:
    tool_id, definition = probe
    expected = next(tool for tool in _baseline() if tool["id"] == tool_id)
    surface = definition.surface()
    projected = catalog.TOOLS_BY_ID[tool_id]["inputs"]
    assert projected == expected["inputs"]
    assert [item["key"] for item in surface] == [
        item["key"] for item in expected["inputs"]
    ]
    assert all(
        not item.get("nullable") and not item.get("collection") for item in surface
    )
    assert all("label" not in item and "ui" not in item for item in surface)
    assert all(item["type"] not in {"artifact", "adapter"} for item in surface)
    exposed_keys = {
        field.capability.key for field in definition.fields if field.exposed
    }
    hidden_keys = {
        cap.key for cap in definition.capabilities.capabilities
    } - exposed_keys
    assert not hidden_keys & {item["key"] for item in projected}

    # Tool identity, canvas, timing and hashing stay on the catalog side.
    tool = catalog.TOOLS_BY_ID[tool_id]
    base = {
        key: value
        for key, value in tool.items()
        if key not in {"schema_hash", "timing"}
    }
    assert tool == expected
    assert catalog._schema_hash(base) == expected["schema_hash"]
    assert (
        catalog._schema_hash({**base, "timing": tool["timing"]})
        != expected["schema_hash"]
    )


def test_semantics_feed_production_but_presentation_is_service_owned(
    probe, monkeypatch
) -> None:
    tool_id, definition = probe
    changed = replace(
        definition,
        fields=tuple(
            exposed(field.capability, default="Recipe prompt")
            if field.capability.key == "prompt"
            else exposed(field.capability, default=3.0, minimum=2.0, maximum=4.0)
            if field.capability.key == "duration_seconds"
            else field
            for field in reversed(definition.fields)
        ),
    )
    monkeypatch.setattr(catalog, PROBES[tool_id], changed)
    tools = catalog._tool_definitions()
    tool = next(item for item in tools if item["id"] == tool_id)
    assert [item["key"] for item in tool["inputs"]] == [
        item["key"] for item in changed.surface()
    ]
    projected = {item["key"]: item for item in tool["inputs"]}
    assert projected["prompt"]["default"] == "Recipe prompt"
    assert projected["prompt"]["required"] is False
    assert projected["duration_seconds"]["default"] == 3.0
    assert projected["duration_seconds"]["ui"] == {
        "min": 2.0,
        "max": 4.0,
        "step": 0.5
        if tool_id in {catalog.T2V_ID, catalog.I2V_ID, catalog.FLF_ID}
        else 0.25,
        "unit": "seconds",
    }
    for semantic, public in zip(changed.surface(), projected.values(), strict=True):
        assert public["key"] == semantic["key"]
        assert public["type"] == semantic["type"]
        assert public.get("role") == semantic.get("role")
        assert public.get("default") == semantic.get("default")
    surface = {item["key"]: item for item in definition.surface()}
    assert surface["seed"]["constraints"] == {"min": 0, "max": 2**64 - 1}
    assert "ui" not in projected["seed"]
    assert "max" in surface["width"]["constraints"]
    assert set(projected["width"]["ui"]) == {"min", "step"}

    baseline = next(item for item in _baseline() if item["id"] == tool_id)
    assert {
        key: value
        for key, value in tool.items()
        if key not in {"inputs", "schema_hash"}
    } == {
        key: value
        for key, value in baseline.items()
        if key not in {"inputs", "schema_hash"}
    }
    assert [item for item in tools if item["id"] != tool_id] == [
        item for item in _baseline() if item["id"] != tool_id
    ]
    assert projected["prompt"]["ui"] == {
        "multiline": True,
        "placeholder": "Describe the shot",
    }
    for item in baseline["inputs"]:
        assert projected[item["key"]]["label"] == item["label"]
    assert all(
        projected[key]["required"] is True
        for key in ("width", "height", "duration_seconds", "seed")
    )
    assert catalog.TOOLS == _baseline()


def test_production_projection_takes_media_labels_from_service(probe) -> None:
    _, policy = probe
    before = deepcopy(policy.surface())
    projected = catalog._video_policy_inputs(
        policy.surface(), {"start_image": "Service first", "end_image": "Service last"}
    )
    media = [item for item in projected if item["type"] == "image"]
    assert [item["label"] for item in media] == ["Service first", "Service last"][
        : len(media)
    ]
    assert policy.surface() == before


def test_recipe_defaults_do_not_mean_optional_wire_inputs(
    probe, tmp_path: Path
) -> None:
    tool_id, definition = probe
    surface = {item["key"]: item for item in definition.surface()}
    expected = next(tool for tool in _baseline() if tool["id"] == tool_id)
    with TestClient(
        create_app(home=tmp_path, token="", executor=FakeRuntime())
    ) as client:
        for key in ("width", "height", "duration_seconds", "seed"):
            assert surface[key]["required"] is False
            assert (
                surface[key]["default"]
                == {"width": 512, "height": 512, "duration_seconds": 5.0, "seed": 0}[
                    key
                ]
            )
            inputs = {
                item["key"]: item.get("default", "unused")
                for item in expected["inputs"]
            }
            del inputs[key]
            response = client.post(
                "/v1/jobs",
                json={
                    "tool_id": tool_id,
                    "schema_revision": expected["schema_revision"],
                    "schema_hash": expected["schema_hash"],
                    "inputs": inputs,
                },
            )
            assert response.status_code == 422
            assert response.json() == {
                "error": {"message": "The request is missing required inputs"}
            }


@pytest.mark.parametrize("available", (True, False))
def test_catalog_endpoint_preserves_frozen_contract(
    tmp_path: Path, available: bool
) -> None:
    runtime = FakeRuntime(
        unavailable_operations=set()
        if available
        else set(catalog.TOOL_OPERATIONS.values())
    )
    expected = []
    for tool in _baseline():
        public = {**tool, "available": available}
        if not public["available"]:
            family = (
                "LTX"
                if tool["id"] in {catalog.T2V_ID, catalog.I2V_ID, catalog.FLF_ID}
                else "Klein"
                if tool["id"] in {catalog.KLEIN_T2I_ID, catalog.KLEIN_TWO_IMAGE_ID}
                else "Wan"
            )
            public["unavailable_reason"] = (
                f"Required {family} model files are not installed"
            )
        expected.append(public)
    with TestClient(create_app(home=tmp_path, token="", executor=runtime)) as client:
        response = client.get("/v1/catalog")
        assert response.status_code == 200
        assert response.json() == {
            "protocol_version": "1.0",
            "engine_version": "0.1.0",
            "bundles": [],
            "tools": expected,
        }


def test_static_catalog_needs_no_configuration_or_binding() -> None:
    script = """
import builtins
import io
import json
import os
import sys
import time
from contextlib import ExitStack
from pathlib import Path
from unittest.mock import patch
import dotenv
import fastapi
from fastapi.responses import FileResponse, JSONResponse
from latentslate_engine.recipe import Artifact, ProductPolicy, Recipe
from latentslate_engine.klein9b.contracts import ArtifactIdentity, Klein9BIdentity
before_env = dict(os.environ)

def forbidden(*args, **kwargs):
    raise AssertionError('static catalog must not configure, inspect artifacts or bind')
dotenv.load_dotenv = forbidden
# Allow normal Python source/bytecode loading, but no application filesystem IO.
with ExitStack() as stack:
    for name in ('open', 'read_text', 'read_bytes', 'stat', 'exists', 'is_file', 'is_dir', 'resolve'):
        stack.enter_context(patch.object(Path, name, forbidden))
    for name in ('open', 'stat', 'listdir', 'scandir'):
        stack.enter_context(patch.object(os, name, forbidden))
    stack.enter_context(patch.object(builtins, 'open', forbidden))
    stack.enter_context(patch.object(io, 'open', forbidden))
    stack.enter_context(patch.object(Artifact, '__init__', forbidden))
    stack.enter_context(patch.object(ArtifactIdentity, '__init__', forbidden))
    stack.enter_context(patch.object(Klein9BIdentity, '__init__', forbidden))
    stack.enter_context(patch.object(Klein9BIdentity, 'from_paths', forbidden))
    stack.enter_context(patch.object(ProductPolicy, 'bind', forbidden))
    stack.enter_context(patch.object(Recipe, '__post_init__', forbidden))
    from latentslate_engine import catalog
    assert catalog._tool_definitions() == catalog.TOOLS
    tools = catalog.TOOLS
assert 'torch' not in sys.modules
assert 'diffusers' not in sys.modules
assert 'transformers' not in sys.modules
assert dict(os.environ) == before_env
assert 'latentslate_engine.klein9b.runtime' not in sys.modules
assert 'latentslate_engine.klein9b.two_image' not in sys.modules
for name in ('latentslate_engine.ltx23.t2v', 'latentslate_engine.ltx23.i2v',
             'latentslate_engine.ltx23.flf', 'latentslate_engine.wan2214b.flf',
             'latentslate_engine.wan2214b.i2v', 'latentslate_engine.wan2214b.pipeline'):
    assert name not in sys.modules
print(json.dumps(tools))
"""
    completed = subprocess.run(
        [sys.executable, "-c", script],
        check=False,
        capture_output=True,
        text=True,
        env={
            key: value
            for key, value in os.environ.items()
            if key
            not in {
                "LATENTSLATE_ENGINE_HOME",
                "LATENTSLATE_WAN_MODEL_ROOT",
                "LATENTSLATE_KLEIN9B_VAE",
            }
        },
    )
    assert completed.returncode == 0, completed.stderr
    assert json.loads(completed.stdout) == _baseline()


def test_unconfigured_model_files_do_not_remove_catalog_tools(
    tmp_path: Path, monkeypatch
) -> None:
    monkeypatch.setattr(service, "load_dotenv", lambda *args: None)
    monkeypatch.delenv("LATENTSLATE_WAN_MODEL_ROOT", raising=False)
    monkeypatch.delenv("LATENTSLATE_KLEIN9B_VAE", raising=False)
    with TestClient(create_app(home=tmp_path, token="")) as client:
        tools = client.get("/v1/catalog").json()["tools"]
        assert all(tool["available"] is False for tool in tools)
        assert [
            {
                key: value
                for key, value in tool.items()
                if key not in {"available", "unavailable_reason"}
            }
            for tool in tools
        ] == _baseline()


@pytest.mark.parametrize("two_image", (False, True))
def test_klein_production_catalog_uses_policy_and_matches_frozen_product(
    two_image,
    monkeypatch,
):
    from latentslate_engine.klein9b.recipes import (
        KLEIN9B_T2I_POLICY,
        KLEIN9B_TWO_IMAGE_EXPLICIT_POLICY,
    )

    tool_id = catalog.KLEIN_TWO_IMAGE_ID if two_image else catalog.KLEIN_T2I_ID
    policy = KLEIN9B_TWO_IMAGE_EXPLICIT_POLICY if two_image else KLEIN9B_T2I_POLICY
    expected = next(tool for tool in _baseline() if tool["id"] == tool_id)
    tool = catalog.TOOLS_BY_ID[tool_id]
    assert tool == expected
    assert tool["inputs"] == catalog._klein_policy_inputs(policy.surface())
    assert tool["schema_hash"] == (
        "sha256:d756bc62e593edd29f3c2c909f3c92fd22d10cb2fb44a2b51bdd93afdb605ed8"
        if two_image
        else "sha256:2e94d609c2db43e883da19fb0c73faa1bef7f3459c916760079f7cedd212c6b3"
    )
    assert all(not item.get("nullable") for item in policy.surface())
    assert "loras" not in {item["key"] for item in tool["inputs"]}
    assert all("ui" not in item and "label" not in item for item in policy.surface())
    semantic = {item["key"]: item for item in policy.surface()}
    public = {item["key"]: item for item in tool["inputs"]}
    for key in ("width", "height", "seed"):
        assert semantic[key]["required"] is False
        assert public[key]["required"] is True
    assert "max" in semantic["width"]["constraints"]
    assert set(public["width"]["ui"]) == {"min", "step"}
    assert "ui" not in public["seed"]

    changed = replace(
        policy,
        fields=tuple(
            replace(field, value=512, minimum=512, maximum=1024, step=32)
            if field.capability.key == "width"
            else field
            for field in reversed(policy.fields)
        ),
    )
    monkeypatch.setattr(
        catalog,
        "KLEIN9B_TWO_IMAGE_EXPLICIT_POLICY" if two_image else "KLEIN9B_T2I_POLICY",
        changed,
    )
    changed_tool = next(t for t in catalog._tool_definitions() if t["id"] == tool_id)
    projected = changed_tool["inputs"]
    assert [item["key"] for item in projected] == [
        item["key"] for item in changed.surface()
    ]
    assert next(item for item in projected if item["key"] == "width") == {
        **public["width"],
        "default": 512,
        "ui": {"min": 512, "step": 32},
    }
    assert changed_tool["canvas"] == tool["canvas"]
    assert changed_tool["schema_hash"] != tool["schema_hash"]
    assert catalog.TOOLS == _baseline()


@pytest.mark.parametrize("tool_id", (catalog.KLEIN_T2I_ID, catalog.KLEIN_TWO_IMAGE_ID))
def test_klein_defaults_nullability_and_wire_presence_remain_distinct(
    tmp_path, tool_id
):
    expected = catalog.TOOLS_BY_ID[tool_id]
    inputs = {item["key"]: item.get("default", "unused") for item in expected["inputs"]}
    with TestClient(
        create_app(home=tmp_path, token="", executor=FakeRuntime())
    ) as client:
        for key in ("width", "height", "seed"):
            for changes, message in (
                (
                    {name: value for name, value in inputs.items() if name != key},
                    "The request is missing required inputs",
                ),
                ({**inputs, key: None}, f"{key} must be an integer"),
            ):
                response = client.post(
                    "/v1/jobs",
                    json={
                        "tool_id": tool_id,
                        "schema_revision": expected["schema_revision"],
                        "schema_hash": expected["schema_hash"],
                        "inputs": changes,
                    },
                )
                assert response.status_code == 422
                assert response.json() == {"error": {"message": message}}


@pytest.fixture(autouse=True)
def isolated_model_paths(monkeypatch):
    monkeypatch.setattr(service, "load_dotenv", lambda *args: None)
    monkeypatch.delenv("LATENTSLATE_WAN_MODEL_ROOT", raising=False)
    monkeypatch.delenv("LATENTSLATE_KLEIN9B_VAE", raising=False)


class RecipeRuntime(FakeRuntime):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.recipes = []

    def generate(self, operation, inputs, output_path, progress=None, *, recipe=None):
        self.recipes.append(recipe)
        assert recipe is not None
        recipe = compile_document(recipe)
        assert (
            recipe.resolve(
                {item["key"]: inputs[item["key"]] for item in recipe.surface()}
            )
            == inputs
        )
        super().generate(operation, inputs, output_path, progress)


def _payload(client, tool):
    inputs = {
        item["key"]: item["default"] for item in tool["inputs"] if "default" in item
    }
    inputs["prompt"] = "A forest clearing"
    for item in tool["inputs"]:
        if item["type"] == "image":
            width = tool["canvas"].get("fixed_width", inputs.get("width")) or 256
            height = tool["canvas"].get("fixed_height", inputs.get("height")) or 256
            asset = client.post(
                "/v1/assets",
                files={
                    "file": (
                        "source.png",
                        _png(width, height),
                        "image/png",
                    )
                },
            ).json()
            inputs[item["key"]] = {"type": "asset", "asset_id": asset["id"]}
    return {
        "tool_id": tool["id"],
        "schema_revision": tool["schema_revision"],
        "schema_hash": tool["schema_hash"],
        "recipe": tool["recipe"],
        "inputs": inputs,
    }


def _finished(client, job_id):
    deadline = time.monotonic() + 5
    while time.monotonic() < deadline:
        job = client.get(f"/v1/jobs/{job_id}").json()
        if job["status"] not in {"queued", "running"}:
            return job
        time.sleep(0.01)
    raise AssertionError("Job did not complete")


def test_all_eight_publish_execute_and_preserve_builtins(tmp_path):
    runtime = RecipeRuntime()
    with TestClient(create_app(home=tmp_path, token="", executor=runtime)) as client:
        builtins = client.get("/v1/catalog").json()["tools"]
        definitions = client.get("/v1/authoring/builtins").json()["recipes"]
        ids = []
        for builtin in definitions:
            record = client.post(
                f"/v1/authoring/builtins/{builtin['key']}/duplicate", json={}
            ).json()
            recipe_id = record["document"]["id"]
            path = f"/v1/authoring/recipes/{recipe_id}/publication"
            assert client.get(path).json()["enabled"] is False
            _materialize(record["document"], tmp_path)
            response = client.put(path, json={"enabled": True})
            assert response.status_code == 200, response.text
            tool = response.json()["tool"]
            assert tool["available"] is True
            assert tool["schema_revision"] == 1
            ids.append(tool["id"])
            payload = _payload(client, tool)
            malformed = deepcopy(payload)
            malformed["recipe"]["revision"] = True
            assert client.post("/v1/jobs", json=malformed).status_code == 409
            accepted = client.post("/v1/jobs", json=payload)
            assert accepted.status_code == 200, accepted.text
            result = _finished(client, accepted.json()["id"])
            assert result["status"] == "succeeded", result
            assert result["recipe"] == tool["recipe"]
            assert result["tool_id"] == tool["id"]
        catalog = client.get("/v1/catalog").json()["tools"]
        assert catalog[:8] == builtins
        assert len(set(ids)) == 8
        assert len(catalog) == 16
        assert len(runtime.recipes) == 8
    with TestClient(
        create_app(home=tmp_path, token="", executor=RecipeRuntime())
    ) as client:
        assert {
            item["id"] for item in client.get("/v1/catalog").json()["tools"][8:]
        } == set(ids)


def test_queued_revision_survives_edit_disable_and_rejects_stale_requests(tmp_path):
    runtime = RecipeRuntime(blocked=True)
    with TestClient(create_app(home=tmp_path, token="", executor=runtime)) as client:
        record = client.post(
            "/v1/authoring/builtins/ltx23.t2v.v1/duplicate", json={}
        ).json()
        _materialize(record["document"], tmp_path)
        recipe_id = record["document"]["id"]
        path = f"/v1/authoring/recipes/{recipe_id}"
        tool = client.put(path + "/publication", json={"enabled": True}).json()["tool"]
        payload = _payload(client, tool)
        first = client.post("/v1/jobs", json=payload).json()
        assert runtime.started.wait(2)
        queued = client.post("/v1/jobs", json=payload).json()
        document = deepcopy(record["document"])
        _field(document, "seed")["value"] = 99
        updated = client.put(path, json={"base_revision": 1, "document": document})
        assert updated.status_code == 200
        assert client.post("/v1/jobs", json=payload).status_code == 409
        latest = client.get(path + "/publication").json()["tool"]
        stale_recipe = _payload(client, latest)
        stale_recipe["recipe"] = tool["recipe"]
        assert client.post("/v1/jobs", json=stale_recipe).status_code == 409
        client.put(path + "/publication", json={"enabled": False})
        assert client.post("/v1/jobs", json=_payload(client, latest)).status_code == 422
        runtime.finish.set()
        for job in (first, queued):
            result = _finished(client, job["id"])
            assert result["status"] == "succeeded"
            assert result["recipe"] == tool["recipe"]
        assert all(
            inputs["seed"] == payload["inputs"]["seed"] for inputs in runtime.inputs
        )


def test_hidden_revision_freshness_stable_identity_and_cross_host_import(tmp_path):
    with TestClient(
        create_app(home=tmp_path / "source", token="", executor=RecipeRuntime())
    ) as client:
        record = client.post(
            "/v1/authoring/builtins/ltx23.t2v.v1/duplicate", json={}
        ).json()
        recipe_id = record["document"]["id"]
        path = f"/v1/authoring/recipes/{recipe_id}"
        # Editing before the first publication does not consume schema revisions.
        document = record["document"]
        _field(document, "seed")["value"] = 123
        record = client.put(
            path, json={"base_revision": 1, "document": document}
        ).json()
        assert "schema" not in record and "enabled" not in record
        _materialize(document, tmp_path)
        original = client.put(path + "/publication", json={"enabled": True}).json()[
            "tool"
        ]
        assert original["schema_revision"] == 1
        old_payload = _payload(client, original)
        document["name"] = "Renamed user recipe"
        _field(document, "transformer_adapter_strengths")["value"] = [0.25]
        updated = client.put(path, json={"base_revision": 2, "document": document})
        assert updated.status_code == 200, updated.text
        latest = client.get(path + "/publication").json()["tool"]
        assert latest["id"] == original["id"] and latest["key"] == original["key"]
        assert latest["schema_hash"] == original["schema_hash"]
        assert latest["schema_revision"] == 1
        assert latest["recipe"]["revision"] == 3
        assert (
            latest["recipe"]["definition_hash"] != original["recipe"]["definition_hash"]
        )
        assert client.post("/v1/jobs", json=old_payload).status_code == 409
        payload = _payload(client, latest)
        for field, value in (("schema_revision", 2), ("schema_hash", "stale")):
            assert (
                client.post("/v1/jobs", json={**payload, field: value}).status_code
                == 409
            )
        stale_hash = deepcopy(payload)
        stale_hash["recipe"]["definition_hash"] = original["recipe"]["definition_hash"]
        assert client.post("/v1/jobs", json=stale_hash).status_code == 409
        submitted = client.post("/v1/jobs", json=payload).json()
        assert _finished(client, submitted["id"])["recipe"] == latest["recipe"]
        exported = client.get(path + "/export").content
        assert b'"enabled"' not in exported and b'"schema"' not in exported
    with TestClient(
        create_app(home=tmp_path / "target", token="", executor=RecipeRuntime())
    ) as target:
        imported = target.post("/v1/authoring/imports", json={"document": document})
        assert imported.status_code == 200
        publication = target.get(path + "/publication").json()
        assert publication["enabled"] is False
        assert len(target.get("/v1/catalog").json()["tools"]) == 8
        assert publication["tool"]["id"] == original["id"]
        assert target.get(path + "/export").content == exported


def test_unavailable_publication_and_builtin_identity_collision(tmp_path, monkeypatch):
    from latentslate_engine import service

    with TestClient(
        create_app(home=tmp_path, token="", executor=RecipeRuntime())
    ) as client:
        record = client.post(
            "/v1/authoring/builtins/ltx23.t2v.v1/duplicate", json={}
        ).json()
        path = f"/v1/authoring/recipes/{record['document']['id']}/publication"
        tool = client.put(path, json={"enabled": True}).json()["tool"]
        assert tool["available"] is False
        assert "does not exist" in tool["unavailable_reason"]
        assert client.get("/v1/catalog").json()["tools"][-1] == tool
        assert client.post("/v1/jobs", json=_payload(client, tool)).status_code == 503
        client.put(path, json={"enabled": False})
        monkeypatch.setattr(
            service.uuid, "uuid5", lambda namespace, name: service.uuid.UUID(T2V_ID)
        )
        assert client.put(path, json={"enabled": True}).status_code == 409
        assert len(client.get("/v1/catalog").json()["tools"]) == 8


def test_fixed_and_mixed_canvas_and_duration_are_public_schema(tmp_path):
    with TestClient(
        create_app(home=tmp_path, token="", executor=RecipeRuntime())
    ) as client:
        record = client.post(
            "/v1/authoring/builtins/ltx23.i2v.v1_1/duplicate", json={}
        ).json()
        document = record["document"]
        path = f"/v1/authoring/recipes/{document['id']}"
        for key, value in (("width", 256), ("height", 256), ("duration_seconds", 2.0)):
            _field(document, key).update(mode="fixed", value=value)
        _materialize(document, tmp_path)
        saved = client.put(path, json={"base_revision": 1, "document": document})
        assert saved.status_code == 200, saved.text
        fixed = client.put(path + "/publication", json={"enabled": True}).json()["tool"]
        keys = {item["key"] for item in fixed["inputs"]}
        assert not keys & {"width", "height", "duration_seconds"}
        assert fixed["canvas"]["fixed_width"] == fixed["canvas"]["fixed_height"] == 256
        assert (
            next(item for item in fixed["inputs"] if item["key"] == "start_image")[
                "image_dimensions"
            ]
            == "match_output_canvas"
        )
        assert fixed["timing"]["duration_seconds"] == {
            "mode": "fixed",
            "value": 2.0,
            "min": 2.0,
            "max": 2.0,
            "step": 0.5,
            "output_frame_counts": [{"duration_seconds": 2.0, "frame_count": 57}],
        }
        accepted = client.post("/v1/jobs", json=_payload(client, fixed))
        assert accepted.status_code == 200, accepted.text
        assert _finished(client, accepted.json()["id"])["status"] == "succeeded"
        bad = _payload(client, fixed)
        wrong = client.post(
            "/v1/assets", files={"file": ("wrong.png", _png(512, 512), "image/png")}
        ).json()
        bad["inputs"]["start_image"] = {"type": "asset", "asset_id": wrong["id"]}
        assert client.post("/v1/jobs", json=bad).status_code == 422
        _field(document, "height").update(mode="exposed", value=320)
        response = client.put(path, json={"base_revision": 2, "document": document})
        assert response.status_code == 200, response.text
        mixed = client.get(path + "/publication").json()["tool"]
        assert (
            mixed["canvas"]["fixed_width"] == 256
            and "fixed_height" not in mixed["canvas"]
        )
        assert (
            next(item for item in mixed["inputs"] if item["key"] == "height")["role"]
            == "height"
        )
        assert (
            mixed["schema_revision"] == 2
            and mixed["schema_hash"] != fixed["schema_hash"]
        )
        _field(document, "width")["value"] = 512
        client.put(
            path, json={"base_revision": 3, "document": document}
        ).raise_for_status()
        resized = client.get(path + "/publication").json()["tool"]
        assert (
            resized["schema_revision"] == 3
            and resized["schema_hash"] != mixed["schema_hash"]
        )
        _field(document, "duration_seconds")["value"] = 3.0
        client.put(
            path, json={"base_revision": 4, "document": document}
        ).raise_for_status()
        retimed = client.get(path + "/publication").json()["tool"]
        assert (
            retimed["schema_revision"] == 4
            and retimed["schema_hash"] != resized["schema_hash"]
        )
        assert retimed["timing"]["duration_seconds"]["output_frame_counts"] == [
            {"duration_seconds": 3.0, "frame_count": 89}
        ]
        _field(document, "duration_seconds").update(
            mode="exposed", minimum=2.0, maximum=3.0
        )
        client.put(
            path, json={"base_revision": 5, "document": document}
        ).raise_for_status()
        ranged = client.get(path + "/publication").json()["tool"]["timing"][
            "duration_seconds"
        ]
        assert "mode" not in ranged and ranged["min"] == 2.0 and ranged["max"] == 3.0
        assert [row["duration_seconds"] for row in ranged["output_frame_counts"]] == [
            2.0,
            2.5,
            3.0,
        ]


def test_ordered_strengths_and_reference_derived_geometry_project_faithfully(tmp_path):
    with TestClient(
        create_app(home=tmp_path, token="", executor=RecipeRuntime())
    ) as client:
        record = client.post(
            "/v1/authoring/builtins/ltx23.t2v.v1/duplicate", json={}
        ).json()
        document = record["document"]
        path = f"/v1/authoring/recipes/{document['id']}"
        strengths = _field(document, "transformer_adapter_strengths")
        strengths.update(mode="exposed", value=[0.5, 0.25], minimum=0.0, maximum=1.0)
        artifacts = _field(document, "transformer_adapter_artifacts")
        artifacts["value"] *= 2
        client.put(
            path, json={"base_revision": 1, "document": document}
        ).raise_for_status()
        original = client.put(path + "/publication", json={"enabled": True}).json()[
            "tool"
        ]
        item = next(
            item for item in original["inputs"] if item["key"] == strengths["key"]
        )
        assert item["type"] == "number" and item["collection"] and item["ordered"]
        assert item["default"] == [0.5, 0.25] and item["ui"] == {"min": 0.0, "max": 1.0}
        strengths["value"].reverse()
        client.put(
            path, json={"base_revision": 2, "document": document}
        ).raise_for_status()
        reordered = client.get(path + "/publication").json()["tool"]
        assert (
            reordered["schema_revision"] == 2
            and reordered["schema_hash"] != original["schema_hash"]
        )
        klein_key = next(
            item["key"]
            for item in client.get("/v1/authoring/builtins").json()["recipes"]
            if item["document"]["operation"] == "flux2_klein9b.two_image"
        )
        record = client.post(
            f"/v1/authoring/builtins/{klein_key}/duplicate", json={}
        ).json()
        document = record["document"]
        for key in ("width", "height"):
            _field(document, key).update(mode="fixed", value=None, nullable=True)
        path = f"/v1/authoring/recipes/{document['id']}"
        client.put(
            path, json={"base_revision": 1, "document": document}
        ).raise_for_status()
        derived = client.put(path + "/publication", json={"enabled": True}).json()[
            "tool"
        ]
        assert not {"fixed_width", "fixed_height"} & derived["canvas"].keys()
        assert not {"width", "height"} & {item["key"] for item in derived["inputs"]}
        assert all("image_dimensions" not in item for item in derived["inputs"])


@pytest.mark.native
@pytest.mark.parametrize(
    "operation",
    (
        "t2v",
        "i2v",
        "flf",
        "klein_t2i",
        "klein_two_image",
        "wan_t2v",
        "wan_i2v",
        "wan_flf",
    ),
)
def test_user_and_builtin_reach_identical_native_boundaries(
    tmp_path, monkeypatch, operation
):
    from latentslate_engine import service
    from latentslate_engine.klein9b import two_image
    from latentslate_engine.klein9b.runtime import Klein9BRuntime
    from latentslate_engine.ltx23 import flf, i2v, t2v
    from latentslate_engine.wan2214b import flf as wan_flf
    from latentslate_engine.wan2214b import i2v as wan_i2v
    from latentslate_engine.wan2214b import pipeline

    ltx_paths = service.LtxModelPaths.from_home(tmp_path)
    klein_paths = service.KleinModelPaths.from_home(tmp_path)
    wan_paths = service.WanModelPaths.from_root(tmp_path / "wan")
    documents = builtin_documents(ltx_paths, klein_paths, wan_paths)
    document = next(
        doc
        for doc in documents.values()
        if service.TOOL_OPERATIONS[service.RECIPE_TO_BUILTIN[doc["operation"]]]
        == operation
    )
    _materialize(document, tmp_path)
    definition = compile_document(document)
    inputs = {
        item["key"]: item["default"]
        for item in definition.surface()
        if "default" in item
    }
    inputs["prompt"] = "A forest clearing"
    for item in definition.surface():
        if item["type"] == "image":
            path = tmp_path / (item["key"] + ".png")
            path.write_bytes(_png(inputs["width"], inputs["height"]))
            inputs[item["key"]] = path
    observed = []

    class LtxBoundary:
        def __init__(self, identity):
            self.identity = identity
            observed.append(("identity", identity))

        def close(self):
            pass

        def generate(self, *, progress=None, **request):
            observed.append(("request", request))
            return SimpleNamespace(save_mp4=lambda path: path.write_bytes(b"boundary"))

    if operation in {"t2v", "i2v", "flf"}:
        module, class_name = {
            "t2v": (t2v, "Ltx23T2VRuntime"),
            "i2v": (i2v, "Ltx23I2VRuntime"),
            "flf": (flf, "Ltx23FlfRuntime"),
        }[operation]
        monkeypatch.setattr(module, class_name, LtxBoundary)

    class KleinBoundary:
        def __init__(self):
            self.identity = None

        ensure_identity = Klein9BRuntime.ensure_identity

        def close(self):
            self.identity = None

        def generate(self, *, identity, output, progress=None, **request):
            self.ensure_identity(identity)
            observed.extend((("identity", identity), ("request", request)))
            output.write_bytes(b"boundary")
            return SimpleNamespace(
                models_reused=False, conditioning_reused=False, reference_reused=False
            )

        generate_two_image = generate

    monkeypatch.setattr(two_image, "Klein9BTwoImageRuntime", KleinBoundary)

    class WanBoundary:
        def __init__(self, recipe, device="cpu"):
            self.recipe = recipe
            self.identity = recipe.identity
            self.device = device
            self._conditioning = self._conditioning_key = None
            self._image_conditioning = self._flf_conditioning = None
            observed.append(("identity", self.identity))

        def destroy(self):
            pass

        def generate(self, *, output_path, progress=None, **request):
            observed.append(("request", request))
            output_path.write_bytes(b"boundary")
            return SimpleNamespace(timings={})

    if operation.startswith("wan_"):
        module, class_name = {
            "wan_t2v": (pipeline, "WanSession"),
            "wan_i2v": (wan_i2v, "WanI2VSession"),
            "wan_flf": (wan_flf, "WanFLFSession"),
        }[operation]
        WanBoundary.replaced = getattr(module, class_name).replaced
        monkeypatch.setattr(module, class_name, WanBoundary)

    def execute(user_document):
        observed.clear()
        request_inputs = definition.resolve(inputs) if user_document else inputs
        messages = iter(
            [
                {
                    "type": "generate",
                    "operation": operation,
                    "inputs": request_inputs,
                    "output_path": tmp_path / "output.bin",
                    "recipe": user_document,
                },
                {"type": "close"},
            ]
        )
        replies = []
        connection = SimpleNamespace(
            recv=lambda: next(messages), send=replies.append, close=lambda: None
        )
        if operation.startswith("wan_"):
            service._wan_worker_main(wan_paths, connection)
        elif operation.startswith("klein_"):
            service._klein_worker_main(klein_paths, connection)
        else:
            service._ltx_worker_main(operation, ltx_paths, connection)
        assert replies[-1]["ok"] is True, replies
        return list(observed)

    builtin_boundary = execute(None)
    user_document = deepcopy(document)
    user_document["id"] = str(uuid4())
    user_document["name"] = "User copy"
    assert execute(user_document) == builtin_boundary
    assert [kind for kind, _ in builtin_boundary] == ["identity", "request"]
